services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: guiinow
      TYPEORM_PASSWORD: 123456
      TYPEORM_DATABASE: tododb
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_LOGGING: 'false'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: guiinow
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tododb
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      - db

volumes:
  postgres_data: