name: todo-microsservice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-todoms-${{ hashFiles('todo-ms/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-todoms-

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Jest Unit/Integration tests
        run: pnpm test

      - name: Run Jest e2e tests
        run: pnpm test:e2e

      - name: Run Jest test coverage
        run: pnpm test:cov

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: todo-ms-test-results
          path: |
            ./todo-ms/coverage